### PR TITLE
Yapf

### PR DESCRIPTION
**Pull request by timspainUCL**
Lint all the files! (with yapf)

### CODE REVIEW

**Comment by mattgillucl** [comment]
Here is a high-level comment from someone unfamiliar with the Kaska code: there seem to be a lot of magic numbers floating around in some of these files, e.g. `watercloudmodel.py`. It may be possible to replace some of these with sensibly-names constants?

**Comment by ilectra** [comment]
@mattgillucl , very good point! Can you please open a new issue and assign to @jgomezdans ?

**Comment by mattgillucl** [comment]
@ilectra, new issue #85 assigned to @jgomezdans

**Comment by dpshelio** [comment]
Closing it as @mattgillucl has done it most of these changes.

**Pull request closed without merging**
