### PR TITLE
Config

### PR DESCRIPTION
**Pull request by mattgillucl**
I think it's ready to merge into master now.

### CODE REVIEW

**Comment by mattgillucl** [comment]
I'm guessing the build is failing because I think I don't have write access to the repo. Could that explain it? The tests work fine on my local branch.

**Comment by timspainUCL** [comment]
No, the branch build is failing due to the problems with too new a version of GDAL. The PR build passes, since that uses a sufficiently old version of GDL, thanks to earlier changes.

**Comment by mattgillucl** [comment]
Oh. Do I need to change anything with my PR?

**Comment by timspainUCL** [comment]
The PR is fine. I wouldn't worry about the branch since it will evaporate once the PR is merged.

**Comment by mattgillucl** [comment]
Fixes #66

**Pull request merged**
